volumes:
  minio_data:
  database_data:
    driver: local

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    entrypoint: ./bin/docker-entrypoint
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    stdin_open: true
    tty: true
